### ISSUE TITLE
Improve usability

### ISSUE THREAD

**Issue by AhmadHakami** [mbzuai-nlp/ArTST#2]
Hey, absolutely, this is one of the best discoveries in the year 2023 and you provide us with significant hope to revolutionize AI in audio tasks and Arabic language

what i have observed is that you do not upload the models separately; instead, you load all of them into the same repository at Huggingface

this makes it challenging for anyone to work on it so please upload them separately, including missing files like config.json, and many other files that you can identify by examining other repositories in the same task uploaded here

Thanks again!

**Comment by Theehawau** [comment]
Hi,

Thank you for your feedback. We're currently working on making separate demos, please find the TTS model [here](https://huggingface.co/spaces/MBZUAI/artst-tts-demo/tree/main ). 

Also you don't absolutely need the config.json file as you can get all model configuration from loading the checkpoint. Please check [here](https://github.com/mbzuai-nlp/ArTST#loading-model) for instructions on how to load. For training configurations please check the bash [scripts](https://github.com/mbzuai-nlp/ArTST/tree/main/scripts) provided for each task.

Please feel free to reach out if you face any more issues.
